#pragma once

#include <SFML/Graphics.hpp>
#include <algorithm>
#include <cmath>
#include "../body/body.hpp"
#include "../misc/settings.hpp"

enum State { setup, setup_circle, setup_uniform, setup_normal, setup_custom, sim };

struct input_settings { State program_state=setup; float zoom=1.0f, center_x=0.0f, center_y=0.0f; int mouse_x=0, mouse_y=0; bool mouse_clicked=false, ctrl_pressed=false, d_pressed=false, m_pressed=false, n_pressed=false, b_pressed=false, c_pressed=false;
#ifdef USE_OCTREE
bool o_pressed=false, p_pressed=false;
#endif
bool f_toggle=false; size_t new_body_index=0; };

inline void process_inputs_sim(sf::RenderWindow& w,input_settings& i,sim_settings& s){while(const auto e=w.pollEvent()){
if(e->is<sf::Event::Closed>()){w.close();}
else if(const auto* x=e->getIf<sf::Event::MouseWheelScrolled>()){
#ifdef USE_OCTREE
if(i.o_pressed){if(x->delta>=0)s.octree_max_node_size=std::max(s.octree_max_node_size+1,(size_t)(s.octree_max_node_size*1.1));else s.octree_max_node_size=std::max((size_t)0,std::min(s.octree_max_node_size-1,(size_t)(s.octree_max_node_size*.9)));}
else if(i.p_pressed)s.octree_tolerance=std::max(0.0f,s.octree_tolerance+.01f*x->delta);else
#endif
i.zoom*=1-((.05f+(int)i.ctrl_pressed*settings::zoom_modifier)*x->delta);}
else if(const auto* x=e->getIf<sf::Event::MouseButtonPressed>()){if(x->button==sf::Mouse::Button::Left){i.mouse_x=x->position.x;i.mouse_y=x->position.y;i.mouse_clicked=true;}}
else if(const auto* x=e->getIf<sf::Event::MouseMoved>()){if(i.mouse_clicked){i.center_x+=(i.zoom+settings::drag_modifier*(int)i.ctrl_pressed)*(x->position.x-i.mouse_x)/100;i.center_y-=(i.zoom+settings::drag_modifier*(int)i.ctrl_pressed)*(x->position.y-i.mouse_y)/100;i.mouse_x=x->position.x;i.mouse_y=x->position.y;}}
else if(const auto* x=e->getIf<sf::Event::MouseButtonReleased>()){if(x->button==sf::Mouse::Button::Left){i.center_x+=(i.zoom+settings::drag_modifier*(int)i.ctrl_pressed)*(x->position.x-i.mouse_x)/100;i.center_y-=(i.zoom+settings::drag_modifier*(int)i.ctrl_pressed)*(x->position.y-i.mouse_y)/100;i.mouse_clicked=false;}}
else if(const auto* x=e->getIf<sf::Event::KeyPressed>()){switch(x->scancode){case sf::Keyboard::Scancode::R:i.zoom=1;i.center_x=i.center_y=0;break;case sf::Keyboard::Scancode::LControl:i.ctrl_pressed=true;break;case sf::Keyboard::Scancode::F:i.f_toggle=!i.f_toggle;break;case sf::Keyboard::Scancode::NumpadPlus:if(i.ctrl_pressed)s.timestep*=1.1f;else s.g*=1.1f;break;case sf::Keyboard::Scancode::NumpadMinus:if(i.ctrl_pressed)s.timestep*=.9f;else s.g*=.9f;break;case sf::Keyboard::Scancode::S:s.g*=-1;break;case sf::Keyboard::Scancode::T:i.program_state=setup;s.max_mass=s.min_mass=2000;s.x_range=s.y_range=25;break;
#ifdef USE_OCTREE
case sf::Keyboard::Scancode::O:i.o_pressed=true;break;case sf::Keyboard::Scancode::P:i.p_pressed=true;break;
#endif
default:break;}}
else if(const auto* x=e->getIf<sf::Event::KeyReleased>()){if(x->scancode==sf::Keyboard::Scancode::LControl)i.ctrl_pressed=false;
#ifdef USE_OCTREE
else if(x->scancode==sf::Keyboard::Scancode::O)i.o_pressed=false;else if(x->scancode==sf::Keyboard::Scancode::P)i.p_pressed=false;
#endif
}}}

inline void process_inputs_setup(sf::RenderWindow& w,std::vector<body>& b,std::vector<sf::CircleShape>& sh,input_settings& i,sim_settings& s){while(const auto e=w.pollEvent()){if(e->is<sf::Event::Closed>())w.close();else if(const auto* x=e->getIf<sf::Event::KeyPressed>()){switch(x->scancode){case sf::Keyboard::Scancode::Num1:case sf::Keyboard::Scancode::Numpad1:i.program_state=setup_circle;break;case sf::Keyboard::Scancode::Num2:case sf::Keyboard::Scancode::Numpad2:i.program_state=setup_uniform;break;case sf::Keyboard::Scancode::Num3:case sf::Keyboard::Scancode::Numpad3:i.program_state=setup_normal;break;case sf::Keyboard::Scancode::Num4:case sf::Keyboard::Scancode::Numpad4:i.program_state=setup_custom;b.clear();sh.clear();s.n=0;break;default:break;}}}}

inline void process_inputs_setup_circle(sf::RenderWindow& w,input_settings& i,sim_settings& s){while(const auto e=w.pollEvent()){if(e->is<sf::Event::Closed>())w.close();else if(const auto* x=e->getIf<sf::Event::MouseButtonPressed>()){if(x->button==sf::Mouse::Button::Left)i.mouse_clicked=true;}else if(const auto* x=e->getIf<sf::Event::MouseButtonReleased>()){if(x->button==sf::Mouse::Button::Left)i.mouse_clicked=false;}else if(const auto* x=e->getIf<sf::Event::MouseMoved>()){if(i.mouse_clicked){float dx=100*i.zoom*(x->position.x/settings::window_width_h-1)-i.center_x,dy=(100/settings::aspect_ratio)*i.zoom*(x->position.y/settings::window_height_h-1)-i.center_y;s.circle_radius=std::sqrt(dx*dx+dy*dy);}}else if(const auto* x=e->getIf<sf::Event::MouseWheelScrolled>()){if(i.d_pressed)s.circle_deviation=std::max(0.0f,s.circle_deviation+.01f*x->delta);else if(i.m_pressed)s.max_mass=std::max(s.min_mass,s.max_mass*(1+.01f*x->delta));else if(i.n_pressed)s.min_mass=std::max(0.0f,std::min(s.max_mass,s.min_mass*(1+.01f*x->delta)));else if(i.b_pressed){if(x->delta>=0)s.n=std::max(s.n+1,(size_t)(s.n*1.1));else s.n=std::max((size_t)0,std::min(s.n-1,(size_t)(s.n*.9)));}else i.zoom*=1-((.05f+(int)i.ctrl_pressed*settings::zoom_modifier)*x->delta);}else if(const auto* x=e->getIf<sf::Event::KeyPressed>()){switch(x->scancode){case sf::Keyboard::Scancode::D:i.d_pressed=true;break;case sf::Keyboard::Scancode::Enter:case sf::Keyboard::Scancode::NumpadEnter:i.program_state=sim;break;case sf::Keyboard::Scancode::LControl:i.ctrl_pressed=true;break;case sf::Keyboard::Scancode::M:i.m_pressed=true;break;case sf::Keyboard::Scancode::N:i.n_pressed=true;break;case sf::Keyboard::Scancode::B:i.b_pressed=true;break;default:break;}}else if(const auto* x=e->getIf<sf::Event::KeyReleased>()){switch(x->scancode){case sf::Keyboard::Scancode::D:i.d_pressed=false;break;case sf::Keyboard::Scancode::LControl:i.ctrl_pressed=false;break;case sf::Keyboard::Scancode::M:i.m_pressed=false;break;case sf::Keyboard::Scancode::N:i.n_pressed=false;break;case sf::Keyboard::Scancode::B:i.b_pressed=false;break;default:break;}}}}

inline void process_inputs_setup_uniform(sf::RenderWindow& w,input_settings& i,sim_settings& s){while(const auto e=w.pollEvent()){if(e->is<sf::Event::Closed>())w.close();else if(const auto* x=e->getIf<sf::Event::MouseWheelScrolled>()){if(i.d_pressed)s.x_range=std::max(0.0f,s.x_range*(1+.01f*x->delta));else if(i.c_pressed)s.y_range=std::max(0.0f,s.y_range*(1+.01f*x->delta));else if(i.m_pressed)s.max_mass=std::max(s.min_mass,s.max_mass*(1+.01f*x->delta));else if(i.n_pressed)s.min_mass=std::max(0.0f,std::min(s.max_mass,s.min_mass*(1+.01f*x->delta)));else if(i.b_pressed){if(x->delta>=0)s.n=std::max(s.n+1,(size_t)(s.n*1.1));else s.n=std::max((size_t)0,std::min(s.n-1,(size_t)(s.n*.9)));}else i.zoom*=1-((.05f+(int)i.ctrl_pressed*settings::zoom_modifier)*x->delta);}else if(const auto* x=e->getIf<sf::Event::KeyPressed>()){switch(x->scancode){case sf::Keyboard::Scancode::D:i.d_pressed=true;break;case sf::Keyboard::Scancode::Enter:case sf::Keyboard::Scancode::NumpadEnter:i.program_state=sim;break;case sf::Keyboard::Scancode::LControl:i.ctrl_pressed=true;break;case sf::Keyboard::Scancode::M:i.m_pressed=true;break;case sf::Keyboard::Scancode::N:i.n_pressed=true;break;case sf::Keyboard::Scancode::B:i.b_pressed=true;break;case sf::Keyboard::Scancode::C:i.c_pressed=true;break;default:break;}}else if(const auto* x=e->getIf<sf::Event::KeyReleased>()){switch(x->scancode){case sf::Keyboard::Scancode::D:i.d_pressed=false;break;case sf::Keyboard::Scancode::LControl:i.ctrl_pressed=false;break;case sf::Keyboard::Scancode::M:i.m_pressed=false;break;case sf::Keyboard::Scancode::N:i.n_pressed=false;break;case sf::Keyboard::Scancode::B:i.b_pressed=false;break;case sf::Keyboard::Scancode::C:i.c_pressed=false;break;default:break;}}}}

inline void process_inputs_setup_custom(sf::RenderWindow& w,std::vector<body>& b,std::vector<sf::CircleShape>& sh,input_settings& i,sim_settings& s){while(const auto e=w.pollEvent()){if(e->is<sf::Event::Closed>())w.close();else if(const auto* x=e->getIf<sf::Event::MouseButtonPressed>()){if(x->button==sf::Mouse::Button::Left){i.mouse_clicked=true;float px=100*i.zoom*(x->position.x/settings::window_width_h-1)-i.center_x,py=-(100/settings::aspect_ratio)*i.zoom*(x->position.y/settings::window_height_h-1)-i.center_y;constexpr float r=2000/settings::mass_radius_factor;b.push_back({2000,r,px,py,0,0});sh.resize(b.size());i.new_body_index=b.size()-1;s.n++;}}else if(const auto* x=e->getIf<sf::Event::MouseButtonReleased>()){if(x->button==sf::Mouse::Button::Left)i.mouse_clicked=false;}else if(const auto* x=e->getIf<sf::Event::MouseWheelScrolled>()){if(i.mouse_clicked){b[i.new_body_index].m=std::max(0.0f,b[i.new_body_index].m*(1+.1f*x->delta));b[i.new_body_index].r=b[i.new_body_index].m/settings::mass_radius_factor;}else i.zoom*=1-((.05f+(int)i.ctrl_pressed*settings::zoom_modifier)*x->delta);}else if(const auto* x=e->getIf<sf::Event::KeyPressed>()){switch(x->scancode){case sf::Keyboard::Scancode::R:b.clear();sh.clear();s.n=0;break;case sf::Keyboard::Scancode::Enter:case sf::Keyboard::Scancode::NumpadEnter:i.program_state=sim;break;case sf::Keyboard::Scancode::LControl:i.ctrl_pressed=true;break;default:break;}}else if(const auto* x=e->getIf<sf::Event::KeyReleased>()){if(x->scancode==sf::Keyboard::Scancode::LControl)i.ctrl_pressed=false;}}}
